name: Daily Insert T-Shirt

on:
  schedule:
    - cron: '0 8 * * *'  # Her gün sabah 08:00'de çalışır (UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v2

      - name: Node.js kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bağımlılıkları yükle
        run: npm install

      - name: Scripti çalıştır
        run: node insertTshirt.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
